### ISSUE TITLE
Support the use of password protected servers

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/Akka.Persistence.Redis#10]
Hi,

Given that we are offering Tls support in akka.remote in 1.5, would it not be a good idea to support Tls connections to Secure Redis servers, requiring a password?

I've looked at this a bit and it appears that the underlying library that we are using for access to Redis doesn't support connections requiring a password. [See this issue](https://github.com/andrew-bn/RedisBoost/issues/6) for more details.

I'm proposing we change to the stack exchange library, as this also supports protocol buffers, as other persistence plugins do, so we would get uniformity across the board.

I'm happy to do the work, if this is something that would be wanted.
Cheers
Sean.

**Comment by alexvaluyskiy** [comment]
We have already changed the underlying library to stackexchange redis
