### ISSUE TITLE
Example HOCON settings are missing the plugin key

### ISSUE THREAD

**Issue by jaydeboer** [akkadotnet/Akka.Persistence.Redis#13]
Being a noob I ran into issues while trying to get started with Akka.Persistence using Redis.  It turns out I had to add `plugin = "akka.persistence.journal.redis"` to the journal settings and `plugin = "akka.persistence.snapshot-store.redis"` to the snapshot-store settings.

**Comment by sean-gilliam** [comment]
Closed via #14
