### ISSUE TITLE
Sentinel support

### ISSUE THREAD

**Issue by senzacionale** [akkadotnet/Akka.Persistence.Redis#41]
Hey,

do you support Sentinel for redis?

Something like:

```
redis {
  sentinel = true
  sentinel-master = "mymaster"  //master name
  sentinels = [{host :"localhost", port: 26379}] // list of sentinel addresses
}
```

**Comment by Aaronontheweb** [comment]
This is supported via the StackExchange.Redis connection strings you can pass into the `akka.persistence.journal.redis` and `akka.persistence.snapshot-store.redis` sections. https://stackexchange.github.io/StackExchange.Redis/Configuration.html
