### ISSUE TITLE
Redis cluster mode support

### ISSUE THREAD

**Issue by ArturChe** [akkadotnet/Akka.Persistence.Redis#93]
Does this plugin support Redis in cluster mode?
I have tried to set up a Redis cluster with 3 masters and 1 slave for each master (6 nodes 1 replica).
With this cluster configuration, I am getting an error:
`Persisting failed due to: StackExchange.Redis.RedisCommandException: Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot    at StackExchange.Redis.ServerSelectionStrategy.Select(Message message)`

Library versions are:
Akka.Persistence.Redis v1.0.0
StackExchange.Redis v1.2.6

**Comment by AxonAnon** [comment]
Hello @ArturChe we have exactly the same question in our project. Have you been able to overcome this problem?
@Aaronontheweb do you have any advice?

**Comment by ArturChe** [comment]
Hi @AxonAnon. We have not found a solution to this problem, unfortunately. So we moved to MongoDB persistence. It works with multiple servers out of the box and the configuration is pretty clear.

**Comment by AxonAnon** [comment]
Thanks @ArturChe We're going to try [Twemproxy](https://github.com/twitter/twemproxy), hopefully it works out.

**Comment by AxonAnon** [comment]
@ArturChe For your information, for what its worth, Twemproxy doesn't work either, it doesn't support transactions.

**Comment by Aaronontheweb** [comment]
We're going to resolve this issue in the next release of Akka.Persistence.Redis.

**Comment by Aaronontheweb** [comment]
Per Marc Gravell 's comment on the StackExchange.Redis:

https://github.com/StackExchange/StackExchange.Redis/issues/838#issuecomment-392320804

Looks like we're going to need to do one of these - and we'll need to add a clustered Redis integration test.

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/Akka.Persistence.Redis/pull/113
